version: '2'
services:
  botapp:
    #    image: "mfrankl/messagebroadcast:2"
    build: .
    restart: always
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./data/:/data/
